apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-ingress-service-role
rules:
- apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
  resources: ["services", "deployments", "ingresses"]
  verbs: ["create", "get", "list", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-ingress-service-rolebinding
subjects:
- kind: ServiceAccount
  name: tekton-deploy
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-ingress-service-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-deploy