apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trigger
spec:
  ingressClassName: nginx
  rules:
  - host: wh.susanta.com.np
    http:
      paths:
      - backend:
          service:
            name: el-github-listener
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - wh.susanta.com.np