apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app
spec:
  workspaces:
    - name: git-source
      description: The git repo
    - name: git-credentials
      description: ssh credentials
    - name: docker-credentials
      description: docker creds
  params:
    - name: gitUrl
      description: Git repository url
      type: string
    - name: gitRevision
      description: Git revision to check out
      default: master
      type: string
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
      type: string
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      type: string
      default: k8s/deploy.yaml
    - name: imageUrl
      description: Image name including repository
      type: string
      default: xuxant/dummy
    - name: imageTag
      description: Image tag
      type: string
      default: "latest"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
        - name: ssh-directory
          workspace: git-credentials
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: build-and-push-image
      taskRef:
        name: kaniko
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: git-source
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
    - name: deploy-to-cluster
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - build-and-push-image
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: pathToYamlFile
          value: $(params.pathToYamlFile)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: $(params.imageTag)
        - name: imageDigest
          value: $(tasks.build-and-push-image.results.IMAGE_DIGEST)